// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonV2.Data;

namespace SalonV2.Migrations
{
    [DbContext(typeof(SalonV2Context))]
    partial class SalonV2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalonV2.Models.Klienci", b =>
                {
                    b.Property<int>("KlienciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlienciId");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("SalonV2.Models.Uslugi", b =>
                {
                    b.Property<int>("UslugiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataRozpo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZak")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlienciId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produkty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UslugiId");

                    b.HasIndex("KlienciId");

                    b.ToTable("Uslugi");
                });

            modelBuilder.Entity("SalonV2.Models.Uslugi", b =>
                {
                    b.HasOne("SalonV2.Models.Klienci", "Klienci")
                        .WithMany("Uslugis")
                        .HasForeignKey("KlienciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
